export const vocab = [
  ["会います", "aimasu", "to meet"],
  ["開けます", "akemasu", "to open"],
  ["あげます", "agemasu", "to give"],
  ["遊びます", "asobimasu", "to play, to socialize"],
  ["集まります", "atsumarimasu", "to collect"],
  ["集めます", "atsumemasu", "to collect"],
  ["洗います", "araimasu", "to wash"],
  ["あります", "arimasu", "to be, to exist"],
  ["歩きます", "arukimasu", "to walk"],
  ["言います", "iimasu", "to say"],
  ["行きます", "ikimasu", "to go"],
  ["急ぎます", "isogimasu", "to hurry"],
  ["います", "imasu", "to be, to exist"],
  ["入れます", "iremasu", "to put in"],
  ["動きます", "ugokimasu", "to move"],
  ["歌います", "utaimasu", "to sing"],
  ["生まれます", "umaremasu", "to be born"],
  ["売ります", "urimasu", "to sell"],
  ["選びます", "erabimasu", "to choose"],
  ["起きます", "okimasu", "to wake up, to get up"],
  ["送ります", "okurimasu", "to send"],
  ["怒ります", "okorimasu", "to get angry"],
  ["教えます", "oshiemasu", "to teach, to tell"],
  ["押します", "oshimasu", "to push"],
  ["落とします", "otoshimasu", "to drop"],
  ["踊ります", "odorimasu", "to dance"],
  ["覚えます", "oboemasu", "to learn, to remember"],
  ["思います", "omoimasu", "to think"],
  ["降ります", "orimasu", "to get off"],
  ["終わります", "owarimasu", "to end"],
  ["買います", "kaimasu", "to buy"],
  ["かいます", "kaimasu", "to keep a pet"],
  ["返します", "kaeshimasu", "to return something"],
  ["帰ります", "kaerimasu", "to go home"],
  ["かかります", "kakarimasu", "to take"],
  ["描きます", "kakimasu", "to draw"],
  ["書きます", "kakimasu", "to write"],
  ["鍵をかけます", "kagiokakemasu", "to lock"],
  ["電話をかけます", "denwaokakemasu", "to make a phone call"],
  ["眼鏡をかけます", "meganeokakemasu", "to wear glasses"],
  ["貸します", "kashimasu", "to lend"],
  ["勝ちます", "kachimasu", "to win"],
  ["被ります", "kaburimasu", "to wear (hats etc)"],
  ["借ります", "karimasu", "to borrow"],
  ["喉が渇きます", "nodogakawakimasu", "to be thirsty"],
  ["考えます", "kangaemasu", "to think"],
  ["頑張ります", "ganbarimasu", "to do one's best, to endure"],
  ["聞きます", "kikimasu", "to hear, to listen"],
  ["聞こえます", "kikoemasu", "to be audible"],
  ["決めます", "kimemasu", "to decide"],
  ["着ます", "kimasu", "to wear"],
  ["曇ります", "kumorimasu", "to be cloudy"],
  ["来ます", "kimasu", "to come"],
  ["答えます", "kotaemasu", "to answer"],
  ["込みます", "komimasu", "to be crowded"],
  ["死にます", "shinimasu", "to die"],
  ["閉めます", "shimemasu", "to close"],
  ["知らせます", "shirasemasu", "to notify"],
  ["知ります", "shirimasu", "to know"],
  ["吸います", "suimasu", "to smoke, to inhale"],
  ["お腹が空いています", "onakagasuiteimasu", "to get hungry"],
  ["捨てます", "sutemasu", "to throw out"],
  ["住みます", "sumimasu", "to live"],
  ["します", "shimasu", "to do"],
  ["座ります", "suwarimasu", "to sit"],
  ["出します", "dashimasu", "to put out, to hand in"],
  ["助けます", "tasukemasu", "to help"],
  ["立ちます", "tachimasu", "to stand up"],
  ["建てます", "tatemasu", "to build"],
  ["食べます", "tabemasu", "to eat"],
  ["違います", "chigaimasu", "to be different, to be wrong"],
  ["使います", "tsukaimasu", "to use"],
  ["疲れます", "tsukaremasu", "to get tired"],
  ["着きます", "tsukimasu", "to arrive"],
  ["作ります", "tsukurimasu", "to make"],
  ["電気をつけます", "denkiotsukemasu", "to switch on (a light)"],
  ["伝えます", "tsutaemasu", "to pass on a message"],
  ["続けます", "tsudukemasu", "to continue"],
  ["できます", "dekimasu", "to be able to"],
  ["手伝います", "tetsudaimasu", "to help"],
  ["出ます", "demasu", "to go out"],
  ["通ります", "toorimasu", "to go through"],
  ["泊まります", "tomarimasu", "to stay somewhere"],
  ["止まります", "tomarimasu", "to stop"],
  ["取ります", "torimasu", "to take"],
  ["写真を撮ります", "shashinotorimasu", "to take a photograph"],
  ["直します", "naoshimasu", "to repair"],
  ["泣きます", "nakimasu", "to cry"],
  ["負けます", "makemasu", "to lose"],
  ["投げます", "nagemasu", "to throw"],
  ["習います", "naraimasu", "to learn"],
  ["なります", "narimasu", "to become"],
  ["脱ぎます", "nugimasu", "to take off (clothes)"],
  ["寝ます", "nemasu", "to sleep, to go to bed"],
  ["登ります", "noborimasu", "to climb"],
  ["飲みます", "nomimasu", "to drink"],
  ["乗ります", "norimasu", "to ride on a method of transport"],
  ["入ります", "hairimasu", "to enter"],
  ["履きます", "hakimasu", "to put on (feet or legs)"],
  ["始めます", "hajimemasu", "to start"],
  ["走ります", "hashirimasu", "to run"],
  ["働きます", "hatarakimasu", "to work"],
  ["話します", "hanashimasu", "to talk"],
  ["払います", "haraimasu", "to pay"],
  ["晴れます", "haremasu", "to be sunny, to clear up"],
  ["弾きます", "hikimasu", "to play a musical instrument"],
  ["引きます", "hikimasu", "to subtract"],
  ["引きます", "hikimasu", "to pull"],
  ["風邪をひきます", "kazeohikimasu", "to catch a cold"],
  ["増えます", "fuemasu", "to increase"],
  ["雨が降ります", "amegafurimasu", "to rain"],
  ["減ります", "herimasu", "to decrease"],
  ["曲がります", "magarimasu", "to turn"],
  ["無くします", "nakushimasu", "to lose"],
  ["間違えます", "machigaemasu", "to make a mistake"],
  ["待ちます", "machimasu", "to wait"],
  ["見えます", "miemasu", "to be visible"],
  ["磨きます", "migakimasu", "to polish"],
  ["見せます", "misemasu", "to show"],
  ["見つけます", "mitsukemasu", "to find"],
  ["見ます", "mimasu", "to see, to watch, to look"],
  ["持ちます", "mochimasu", "to hold, to carry"],
  ["持って行きます", "motteikimasu", "to take something"],
  ["持って来ます", "mottekimasu", "to bring something"],
  ["戻ります", "modorimasu", "to return"],
  ["貰います", "moraimasu", "to receive"],
  ["休みます", "yasumimasu", "to rest"],
  ["雨が止みます", "amegayamimasu", "to stop (raining)"],
  ["辞めます", "yamemasu", "to quit"],
  ["呼びます", "yobimasu", "to call"],
  ["読みます", "yomimasu", "to read"],
  ["分かります", "wakarimasu", "to understand"],
  ["忘れます", "wasuremasu", "to forget"],
  ["笑います", "waraimasu", "to laugh"],
  ["運転します", "untenshimasu", "drive"],
  ["運動します", "undoushimasu", "exercise"],
  ["キャンセルします", "kyanserushimasu", "cancel"],
  ["コピーします", "kopiishimasu", "photocopy"],
  ["失敗します", "shippaishimasu", "failure"],
  ["紹介します", "shoukaishimasu", "introduce"],
  ["成功します", "seikoushimasu", "success"],
  ["説明します", "setsumeishimasu", "explain"],
  ["洗濯します", "sentakushimasu", "washing"],
  ["選択します", "sentakushimasu", "select"],
  ["注文します", "chuumonshimasu", "order"],
  ["勉強します", "benkyoushimasu", "study"],
  ["返事します", "henjishimasu", "reply"],
  ["約束します", "yakusokushimasu", "promise"],
  ["掃除します", "soujishimasu", "to clean"],
  ["明るい", "akarui", "bright"],
  ["暖かい", "atatakai", "warm"],
  ["新しい", "atarashii", "new"],
  ["暑い", "atsui", "hot (climate)"],
  ["熱い", "atsui", "hot (to touch)"],
  ["危ない", "abunai", "dangerous"],
  ["いい", "ii", "good"],
  ["忙しい", "isogashii", "busy"],
  ["痛い", "itai", "painful"],
  ["うるさい", "urusai", "noisy"],
  ["嬉しい", "ureshii", "happy, pleased"],
  ["美味しい", "oishii", "tasty"],
  ["多い", "ooi", "many"],
  ["大きい", "ookii", "large, big"],
  ["可笑しい", "okashii", "funny"],
  ["遅い", "osoi", "slow, late"],
  ["面白い", "omoshiroi", "interesting"],
  ["悲しい", "kanashii", "sad"],
  ["可愛い", "kawaii", "cute"],
  ["汚い", "kitanai", "dirty"],
  ["厳しい", "kibishii", "strict, tough"],
  ["暗い", "kurai", "dark"],
  ["こわい", "kowai", "scary"],
  ["寒い", "samui", "cold"],
  ["少ない", "sukunai", "few"],
  ["すごい", "sugoi", "fantastic"],
  ["涼しい", "suzushii", "cool"],
  ["素晴らしい", "subarashii", "wonderful"],
  ["高い", "takai", "high, expensive"],
  ["正しい", "tadashii", "correct"],
  ["楽しい", "tanoshii", "enjoyable"],
  ["小さい", "chiisai", "small"],
  ["近い", "chikai", "near"],
  ["つまらない", "tsumaranai", "boring"],
  ["冷たい", "tsumetai", "cold (to touch)"],
  ["強い", "tsuyoi", "strong"],
  ["遠い", "tooi", "far"],
  ["長い", "nagai", "long"],
  ["早い", "hayai", "early"],
  ["速い", "hayai", "fast"],
  ["古い", "furui", "old"],
  ["欲しい", "hoshii", "desirable"],
  ["まずい", "mazui", "horrible to taste"],
  ["丸い", "marui", "round"],
  ["短い", "mijikai", "short"],
  ["蒸し暑い", "mushiatsui", "hot and sticky"],
  ["難しい", "muzukashii", "difficult"],
  ["珍しい", "mezurashii", "unusual, rare"],
  ["優しい", "yasashii", "kind"],
  ["安い", "yasui", "cheap"],
  ["良い", "yoi", "good"],
  ["弱い", "yowai", "weak"],
  ["若い", "wakai", "young"],
  ["悪い", "warui", "bad"],
  ["嫌な", "iyana", "dislikeable"],
  ["色々な", "iroirona", "various"],
  ["美味しそうな", "oishisouna", "looks tasty"],
  ["大きな", "ookina", "large, big"],
  ["嫌いな", "kiraina", "dislikeable"],
  ["綺麗な", "kireina", "beautiful, pretty, clean"],
  ["元気な", "genkina", "lively, energentic, healthy"],
  ["静かな", "shizukana", "quiet"],
  ["十分な", "juubunna", "sufficient"],
  ["上手な", "jouzuna", "good at"],
  ["心配な", "shinpaina", "worrying"],
  ["好きな", "sukina", "likeable"],
  ["素敵な", "sutekina", "lovely"],
  ["大好きな", "daisukina", "that which I love"],
  ["大変な", "taihenna", "hard, troublesome"],
  ["だめな", "damena", "no good"],
  ["小さな", "chiisana", "small"],
  ["得意な", "tokuina", "good at"],
  ["苦手な", "nigatena", "bad at"],
  ["賑やかな", "nigiyakana", "lively, noisy"],
  ["ハンサムな", "hansamuna", "handsome"],
  ["暇な", "himana", "having free time"],
  ["不便な", "fubenna", "inconvenient"],
  ["下手な", "hetana", "bad at"],
  ["便利な", "benrina", "convenient"],
  ["真面目な", "majimena", "studious, hard working, serious"],
  ["無理な", "murina", "impossible, difficult"],
  ["有名な", "yuumeina", "famous"],
  ["あまり...ない", "amari...nai", "not much"],
  ["一生懸命", "isshoukenmei", "to the best of one's ability"],
  ["一緒に", "isshoni", "together"],
  ["いつも", "itsumo", "always"],
  ["すぐに", "suguni", "immediately"],
  ["少し", "sukoshi", "a little"],
  ["ずっと", "zutto", "continuously"],
  ["全然", "zenzen", "not at all"],
  ["だいたい", "daitai", "more or less"],
  ["たくさん", "takusan", "a lot of"],
  ["例えば", "tatoeba", "for example"],
  ["だんだん", "dandan", "gradually"],
  ["ちょうど", "choudo", "exactly"],
  ["ちょっと", "chotto", "a little"],
  ["時々", "tokidoki", "sometimes"],
  ["特に", "tokuni", "especially"],
  ["とても", "totemo", "very"],
  ["初めて", "hajimete", "for the first time"],
  ["ほとんど", "hotondo", "mostly"],
  ["本当に", "hontouni", "truly"],
  ["また", "mata", "again"],
  ["まだ", "mada", "not yet"],
  ["まっすぐ", "massugu", "straight"],
  ["もう", "mou", "already"],
  ["もうすぐ", "mousugu", "soon"],
  ["もちろん", "mochiron", "of course"],
  ["もっと", "motto", "more"],
  ["ゆっくり", "yukkuri", "slowly"],
  ["よく", "yoku", "often, well"],
  ["間", "aida", "in between"],
  ["上", "ue", "on, above"],
  ["後ろ", "ushiro", "behind"],
  ["...がわ", "...gawa", "...'s side"],
  ["下", "shita", "below, beneath"],
  ["外", "soto", "outside"],
  ["そば", "soba", "nearby"],
  ["近く", "chikaku", "near"],
  ["遠く", "tooku", "far away"],
  ["隣", "tonari", "next to"],
  ["中", "naka", "in, inside"],
  ["反対", "hantai", "opposite"],
  ["前", "mae", "in front of"],
  ["周り", "mawari", "around"],
  ["真ん中", "mannaka", "right in the middle"],
  ["向かい", "mukai", "facing"],
  ["よこ", "yoko", "next to"],
  ["色", "iro", "colours"],
  ["青い", "aoi", "blue"],
  ["赤い", "akai", "red"],
  ["オレンジ", "orenji", "orange"],
  ["黄色い", "kiiroi", "yellow"],
  ["金", "kin", "gold"],
  ["銀", "gin", "silver"],
  ["グレー", "gure-", "grey"],
  ["黒い", "kuroi", "black"],
  ["白い", "shiroi", "white"],
  ["茶色い", "chairoi", "brown"],
  ["灰色", "haiiro", "grey"],
  ["ピンク", "pinku", "pink"],
  ["緑色", "midori", "green"],
  ["紫色", "murasaki", "purple"],
  ["ゼロ", "zero", "zero"],
  ["れい", "rei", "zero"],
  ["一", "ichi", "one"],
  ["二", "ni", "two"],
  ["三", "san", "three"],
  ["四", "shi", "four"],
  ["四", "yon", "four"],
  ["五", "go", "five"],
  ["六", "roku", "six"],
  ["七", "nana", "seven"],
  ["七", "shichi", "seven"],
  ["八", "hachi", "eight"],
  ["九", "kyuu", "nine"],
  ["十", "juu", "ten"],
  ["十一、十二...", "juuichijuuni...", "eleven, twelve..."],
  ["二十一、二十二...", "nijuuichinijuuni...", "twenty-one, twenty-two..."],
  ["九十九", "tsukumo", "ninety-nine"],
  ["百", "hyaku", "one hundred"],
  ["千", "sen", "one thousand"],
  ["万", "man", "ten thousand"],
  ["一億", "ichioku", "a hundred million"],
  ["一つ", "hitotsu", "one"],
  ["二つ", "futatsu", "two"],
  ["三つ", "mittsu", "three"],
  ["四つ", "yottsu", "four"],
  ["五つ", "itsutsu", "five"],
  ["六つ", "muttsu", "six"],
  ["七つ", "nanatsu", "seven"],
  ["八つ", "yattsu", "eight"],
  ["九つ", "kokonotsu", "nine"],
  ["十", "too", "ten"],
  ["一つ目、二つ目...", "hitotsumefutatsume", "first, second..."],
  ["一番、二番...", "ichibanniban", "first, second..."],
  ["一番目、二番目...", "ichibanmenibanme", "first, second..."],
  ["マイナス", "mainasu", "minus"],
  ["プラス", "purasu", "plus"],
  ["円", "en", "yen"],
  ["ドル", "doru", "dollars"],
  ["ポンド", "pondo", "pound sterling"],
  ["ユーロ", "yu-ro", "Euro"],
  ["回", "kai", "counter for number of times"],
  ["階", "kai", "counter for number of floors"],
  ["缶", "kan", "a (metal) can"],
  ["個", "ko", "general counter"],
  ["才", "sai", "years old"],
  ["冊", "satsu", "counter for books"],
  ["台", "dai", "counter for machines, vehicles"],
  ["点", "ten", "marks, points"],
  ["人", "nin", "counter for people"],
  ["杯", "hai", "cup fulls"],
  ["泊", "haku", "counter for number of nights"],
  ["匹", "hiki", "counter for small animals"],
  ["匹", "piki", "counter for small animals"],
  ["瓶", "bin", "a bottle"],
  ["本", "hon", "counter for long, thin, cylindrical things"],
  ["枚", "mai", "counter for flat things"],
  ["一人", "hitori", "one person"],
  ["二人", "futari", "two people"],
  ["番号", "bangou", "number"],
  ["半分", "hanbun", "half"],
  ["ぐらい", "gurai", "about (quantities)"],
  ["ごろ", "goro", "about (times)"],
  ["キロ", "kiro", "kilometre, kilogramme"],
  ["グラム", "guramu", "gramme"],
  ["センチ", "senchi", "centimetre"],
  ["メートル", "me-toru", "metre"],
  ["同じ", "onaji", "the same"],
  ["全く同じ", "mattakuonaji", "exactly the same"],
  ["後で", "atode", "later"],
  ["最後に", "saigoni", "lastly"],
  ["最初に", "saishoni", "firstly"],
  ["そして", "soshite", "and"],
  ["それから", "sorekara", "and then"],
  ["それに", "soreni", "moreover"],
  ["だから", "dakara", "therefore"],
  ["次に", "tsugini", "next"],
  ["でも", "demo", "but"],
  ["先ず", "mazu", "firstly"],
  ["午前", "gozen", "am"],
  ["午後", "gogo", "pm"],
  ["今日", "kyou", "today"],
  ["明日", "ashita", "tomorrow"],
  ["明後日", "asatte", "the day after tomorrow"],
  ["昨日", "kinou", "yesterday"],
  ["一昨日", "ototoi", "the day before yesterday"],
  ["毎日", "mainichi", "every day"],
  ["今週", "konshuu", "this week"],
  ["先週", "senshuu", "last week"],
  ["来週", "raishuu", "next week"],
  ["再来週", "saraishuu", "the week after the next"],
  ["毎週", "maishuu", "every week"],
  ["今月", "kongetsu", "this month"],
  ["来月", "raigetsu", "next month"],
  ["再来月", "saraigetsu", "the month after the next"],
  ["先月", "sengetsu", "last month"],
  ["毎月", "maitsuki", "every month"],
  ["今年", "kotoshi", "this year"],
  ["来年", "rainen", "next year"],
  ["再来年", "sarainen", "the year after the next"],
  ["一昨年", "ototoshi", "the year before the last"],
  ["去年", "kyonen", "last year"],
  ["毎年", "maitoshi", "every year"],
  ["...日", "...nichi", "... days"],
  ["...週間", "...shuukan", "... weeks"],
  ["...年", "...nen", "... years"],
  ["今", "ima", "now"],
  ["...時...分", "...ji...fun", "... minutes past ..."],
  ["...時半", "...jihan", "half past ..."],
  ["秒", "byou", "seconds"],
  ["午前中", "gozenchuu", "during the morning"],
  ["時間", "jikan", "time"],
  ["...時間", "...jikan", "length of time"],
  ["一年中", "ichinenjuu", "all year round"],
  ["朝", "asa", "morning"],
  ["晩", "ban", "evening"],
  ["毎朝", "maiasa", "every morning"],
  ["毎晩", "maiban", "every evening"],
  ["夜", "yoru", "night"],
  ["今晩", "konban", "this evening"],
  ["日", "hi", "day"],
  ["昔", "mukashi", "in the past"],
  ["月曜日", "getsuyoubi", "Monday"],
  ["火曜日", "kayoubi", "Tuesday"],
  ["水曜日", "suiyoubi", "Wednesday"],
  ["木曜日", "mokuyoubi", "Thursday"],
  ["金曜日", "kinyoubi", "Friday"],
  ["土曜日", "doyoubi", "Saturday"],
  ["日曜日", "nichiyoubi", "Sunday"],
  ["週まつ", "shuumatsu", "weekend"],
  ["休日", "kyuujitsu", "holiday"],
  ["祝日", "shukujitsu", "festival day"],
  ["一月", "ichigatsu", "January"],
  ["二月", "nigatsu", "February"],
  ["三月", "sangatsu", "March"],
  ["四月", "shigatsu", "April"],
  ["五月", "gogatsu", "May"],
  ["六月", "rokugatsu", "June"],
  ["七月", "shichigatsu", "July"],
  ["八月", "hachigatsu", "August"],
  ["九月", "kugatsu", "September"],
  ["十月", "juugatsu", "October"],
  ["十一月", "juuichigatsu", "November"],
  ["十二月", "juunigatsu", "December"],
  ["季節", "kisetsu", "season"],
  ["春", "haru", "spring"],
  ["梅雨", "tsuyu", "rainy season"],
  ["夏", "natsu", "summer"],
  ["秋", "aki", "autumn"],
  ["冬", "fuyu", "winter"],
  ["いくら", "ikura", "how much (money)"],
  ["いつ", "itsu", "when"],
  ["誰", "dare", "who"],
  ["どう", "dou", "how"],
  ["どうして", "doushite", "why"],
  ["どうやって", "douyatte", "how"],
  ["どこ", "doko", "where"],
  ["どの", "dono", "which"],
  ["どのくらい", "donokurai", "how much (quantity)"],
  ["どれ", "dore", "which one"],
  ["どんな", "donna", "what kind of"],
  ["何", "nani", "what"],
  ["何色", "naniiro", "what colour"],
  ["何...", "nan...", "what (day/month/...)"],
  ["何月", "nangatsu", "which month"],
  ["何時", "nanji", "what time"],
  ["何日", "nannichi", "what date"],
  ["何曜日", "nanyoubi", "what day of the week"],
  ["...くん", "...kun", "used after a boy's name"],
  ["...さん", "...san", "Mr./Mrs./Ms."],
  ["...さま", "...sama", "Mr./Mrs./Ms."],
  ["...でございます", "...degozaimasu", "to be, to exist (honorific)"],
  ["あのう", "anou", "well..."],
  ["ありがとうございます", "arigatougozaimasu", "thank you (very much)"],
  ["いいですね", "iidesune", "that's nice"],
  ["いいですよ", "iidesuyo", "that's fine"],
  ["いただきます", "itadakimasu", "bon apetite"],
  ["いらっしゃいませ", "irasshaimase", "welcome"],
  ["行ってきます", "ittekimasu", "I'm off"],
  ["いってらっしゃい", "itterasshai", "see you later / take care"],
  ["ただいま", "tadaima", "I'm home"],
  ["お帰りなさい", "okaerinasai", "welcome home"],
  ["おかげさまで", "okagesamade", "thanks for asking"],
  ["お元気ですか", "ogenkidesuka", "how are you?"],
  ["お大事に", "odaijini", "take care (to an ill person)"],
  ["お願いします", "onegaishimasu", "please"],
  ["おはようございます", "ohayougozaimasu", "good morning"],
  ["お休みなさい", "oyasuminasai", "good night"],
  ["かしこまりました", "kashikomarimashita", "certainly"],
  ["がんばってください", "ganbattekudasai", "do your best"],
  ["ごちそうさまでした", "gochisousamadeshita", "thanks for the meal"],
  ["ごめんなさい", "gomennasai", "I'm sorry"],
  ["こんにちは", "konnichiha", "hello"],
  ["こんばんは", "konbanha", "good evening"],
  ["さようなら", "sayounara", "goodbye"],
  ["残念ですが", "zannendesuga", "it's a pity, but.."],
  ["じゃ", "ja", "well then, in that case"],
  ["じゃ、また", "jamata", "see you again"],
  ["すみません", "sumimasen", "sorry, excuse me, thanks"],
  ["全部で", "zenbude", "in total"],
  ["大丈夫です", "daijoubudesu", "I'm/It's okay"],
  ["ちょっと...", "chotto...", "it’s a bit..."],
  ["都合が悪いです", "tsugougawaruidesu", "it's inconvenient"],
  ["どうぞ", "douzo", "said when giving things"],
  ["どうも", "doumo", "thanks"],
  ["はい", "hai", "yes"],
  ["いいえ", "iie", "no"],
  ["ええ", "ee", "yes (familiar)"],
  ["うん", "un", "yes (familiar)"],
];
