export const vocab = [
    ["明るい", "akarui", "bright"],
    ["暖かい", "atatakai", "warm"],
    ["新しい", "atarashii", "new"],
    ["暑い", "atsui", "hot (climate)"],
    ["熱い", "atsui", "hot (to touch)"],
    ["危ない", "abunai", "dangerous"],
    ["いい", "ii", "good"],
    ["忙しい", "isogashii", "busy"],
    ["痛い", "itai", "painful"],
    ["うるさい", "urusai", "noisy"],
    ["嬉しい", "ureshii", "happy, pleased"],
    ["美味しい", "oishii", "tasty"],
    ["多い", "ooi", "many"],
    ["大きい", "ookii", "large, big"],
    ["可笑しい", "okashii", "funny"],
    ["遅い", "osoi", "slow, late"],
    ["面白い", "omoshiroi", "interesting"],
    ["悲しい", "kanashii", "sad"],
    ["可愛い", "kawaii", "cute"],
    ["汚い", "kitanai", "dirty"],
    ["厳しい", "kibishii", "strict, tough"],
    ["暗い", "kurai", "dark"],
    ["こわい", "kowai", "scary"],
    ["寒い", "samui", "cold"],
    ["少ない", "sukunai", "few"],
    ["すごい", "sugoi", "fantastic"],
    ["涼しい", "suzushii", "cool"],
    ["素晴らしい", "subarashii", "wonderful"],
    ["高い", "takai", "high, expensive"],
    ["正しい", "tadashii", "correct"],
]